# See full config at https://github.com/backup-manager/symfony
bm_backup_manager:
    database:
        daily_expense:
            dsn: '%env(resolve:DATABASE_URL)%'
    storage:
        local:
            type: Local
            root: '%kernel.project_dir%/data/db_backup'
