#####################
# Security
#####################
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

#####################
# Pages
#####################
app_dashboard:
    path: /
    controller: App\Controller\DashboardController::view
    methods: GET

app_records:
    path: /records
    controller: App\Controller\EntityController::records
    methods: GET

app_entity_categories:
    path: /entity/categories
    controller: App\Controller\EntityController::categories
    methods: GET

app_entity_accounts:
    path: /entity/accounts
    controller: App\Controller\EntityController::accounts
    methods: GET

app_entity_owners:
    path: /entity/owners
    controller: App\Controller\EntityController::owners
    methods: GET

app_entity_currencies:
    path: /entity/currencies
    controller: App\Controller\EntityController::currencies
    methods: GET

#####################
# APIs
#####################
app_api_get_currency:
    path: /api/currency/{id}
    controller: App\Controller\Api\CurrencyController::fetch
    methods: GET
    requirements:
        id: '\d+'
    options:
        expose: true

app_api_update_currency:
    path: /api/currency/{id}
    controller: App\Controller\Api\CurrencyController::update
    methods: PUT
    requirements:
        id: '\d+'
    options:
        expose: true

app_api_add_currency:
    path: /api/currency
    controller: App\Controller\Api\CurrencyController::create
    methods: POST
    options:
        expose: true

app_api_delete_currency:
    path: /api/currency/{id}
    controller: App\Controller\Api\CurrencyController::delete
    methods: DELETE
    requirements:
        id: '\d+'
    options:
        expose: true

app_api_get_account:
    path: /api/account/{id}
    controller: App\Controller\Api\AccountController::fetch
    methods: GET
    requirements:
        id: '\d+'
    options:
        expose: true

app_api_update_account:
    path: /api/account/{id}
    controller: App\Controller\Api\AccountController::update
    methods: PUT
    requirements:
        id: '\d+'
    options:
        expose: true

app_api_add_account:
    path: /api/account
    controller: App\Controller\Api\AccountController::create
    methods: POST
    options:
        expose: true

app_api_delete_account:
    path: /api/account/{id}
    controller: App\Controller\Api\AccountController::delete
    methods: DELETE
    requirements:
        id: '\d+'
    options:
        expose: true
